services:
  todoapp:
    build: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=mydatabase
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydatabase